# Generated by Django 5.1 on 2024-08-31 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
    ]
